/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Activities: () => import('#controllers/activities_controller'),
  Contributions: () => import('#controllers/contributions_controller'),
  ExpenseCategories: () => import('#controllers/expense_categories_controller'),
  Expenses: () => import('#controllers/expenses_controller'),
  Investors: () => import('#controllers/investors_controller'),
  Roles: () => import('#controllers/roles_controller'),
  Users: () => import('#controllers/users_controller'),
}
