/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BudgetCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'syncedAt'] as const
  $columns = BudgetCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime()
  declare syncedAt: DateTime | null
}

export class ContributionSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'id', 'investorId', 'method', 'note', 'paidAt', 'recordedBy', 'syncedAt'] as const
  $columns = ContributionSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare investorId: string
  @column()
  declare method: string | null
  @column()
  declare note: string | null
  @column.dateTime()
  declare paidAt: DateTime
  @column()
  declare recordedBy: string
  @column.dateTime()
  declare syncedAt: DateTime | null
}

export class ExpenseSchema extends BaseModel {
  static $columns = ['amount', 'categoryId', 'createdAt', 'description', 'id', 'receiptPhotoPath', 'recordedBy', 'reversesExpenseId', 'spentAt', 'syncedAt'] as const
  $columns = ExpenseSchema.$columns
  @column()
  declare amount: number
  @column()
  declare categoryId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare receiptPhotoPath: string | null
  @column()
  declare recordedBy: string
  @column()
  declare reversesExpenseId: string | null
  @column.dateTime()
  declare spentAt: DateTime
  @column.dateTime()
  declare syncedAt: DateTime | null
}

export class InvestorSchema extends BaseModel {
  static $columns = ['agreedContribution', 'createdAt', 'createdBy', 'id', 'joinedAt', 'name', 'phone', 'syncedAt', 'updatedAt', 'userId'] as const
  $columns = InvestorSchema.$columns
  @column()
  declare agreedContribution: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare joinedAt: DateTime
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column.dateTime()
  declare syncedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class RefreshTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'revokedAt', 'tokenHash', 'userId'] as const
  $columns = RefreshTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare tokenHash: string
  @column()
  declare userId: string
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'label'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'email', 'id', 'isActive', 'name', 'password', 'phone', 'roleId', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare roleId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
