/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type InvestorTransformer from '#transformers/investor_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Investor = InferData<InvestorTransformer>
  export namespace Investor {
    export type Variants = InferVariants<InvestorTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
